language: python

python:
- pypy
- pypy3
- 2.6
- 2.7
- 3.4
- 3.5

sudo: false

install:
- if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi
- python setup.py install
- make README.rst

script:
- python setup.py test
